name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_avif: ^2.3.0
  provider: ^6.0.1
  path_provider: ^2.0.2
  faker: ^2.1.0
  intl: ^0.19.0
  mobile_scanner: ^3.5.5
  qris: ^0.7.1
  barcode_finder: ^0.0.5
  image_picker: ^1.0.4
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  firebase_database: ^10.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - images/sampah1.avif
    - images/sampah2.avif
