// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_mlYc84taSShyPVvlLOIA8JEG7oiDRjA',
    appId: '1:680043467764:web:8d259e2bcbc89b1652dfa1',
    messagingSenderId: '680043467764',
    projectId: 'recykals',
    authDomain: 'recykals.firebaseapp.com',
    databaseURL: 'https://recykals-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'recykals.appspot.com',
    measurementId: 'G-DMDY7QQRVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAgJXOOQNvjnBZ4Dr_4RZiX-ZJYF3KZ0E',
    appId: '1:680043467764:android:d1ff82ca0ebbba0752dfa1',
    messagingSenderId: '680043467764',
    projectId: 'recykals',
    databaseURL: 'https://recykals-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'recykals.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdc1vbesDLsdJRu0pRgHQW1UOt0QNjzto',
    appId: '1:680043467764:ios:767b88dff364b1b952dfa1',
    messagingSenderId: '680043467764',
    projectId: 'recykals',
    databaseURL: 'https://recykals-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'recykals.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdc1vbesDLsdJRu0pRgHQW1UOt0QNjzto',
    appId: '1:680043467764:ios:767b88dff364b1b952dfa1',
    messagingSenderId: '680043467764',
    projectId: 'recykals',
    databaseURL: 'https://recykals-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'recykals.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_mlYc84taSShyPVvlLOIA8JEG7oiDRjA',
    appId: '1:680043467764:web:3b8288db7cbd620752dfa1',
    messagingSenderId: '680043467764',
    projectId: 'recykals',
    authDomain: 'recykals.firebaseapp.com',
    databaseURL: 'https://recykals-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'recykals.appspot.com',
    measurementId: 'G-Q2VXEJS728',
  );

}